-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE VIEW "public"."games" AS (SELECT pk, game_guid, game_type, season, game_date, official_date, day_night, double_header, game_number, scheduled_innings, games_in_series, series_game_number, series_description, venue_pk, home_club_pk, home_score, home_is_winner, away_club_pk, away_score, away_is_winner, abstract_game_state, coded_game_state, detailed_state FROM sqlmesh__public.public__games__3884609178);--> statement-breakpoint
CREATE VIEW "public"."woba_weights" AS (SELECT pk, woba, woba_scale, wbb, whbp, w1b, w2b, w3b, whr, run_sb, run_cs, r_pa, r_w, c_fip FROM sqlmesh__public.public__woba_weights__3211996326);--> statement-breakpoint
CREATE VIEW "public"."people" AS (SELECT pk, person_id, uuid, retro_id, bbref_id, bbref_minors_id, fangraphs_id, last_name, first_name, given_name, suffix, nickname, birth_date, death_date, mlb_debut_year, mlb_last_season FROM sqlmesh__public.public__people__1739420493);--> statement-breakpoint
CREATE VIEW "public"."club_game_results" AS (SELECT game_pk, club_pk, season, game_date, day_night, double_header, is_home, did_win FROM sqlmesh__public.public__club_game_results__3834347490);--> statement-breakpoint
CREATE VIEW "public"."pitching_stats_season" AS (SELECT pitcher_pk, season, pa, ip, outs, h, singles, doubles, triples, home_runs, bb, ibb, hbp, so, sf, sh, runs, earned_runs, era, whip, k9, bb9, hr9, babip, fip, lob_pct, qualified FROM sqlmesh__public.public__pitching_stats_season__1191742444);--> statement-breakpoint
CREATE VIEW "public"."sports" AS (SELECT pk, code, name, abbreviation, sort_order, active FROM sqlmesh__public.public__sports__1261206631);--> statement-breakpoint
CREATE VIEW "public"."clubs_history" AS (SELECT pk, club_pk, season, name, team_name, club_name, franchise_name, short_name, location_name, abbreviation, team_code, file_code, first_year_of_play, active, sport_pk, league_pk, division_pk, venue_pk FROM sqlmesh__public.public__clubs_history__73235740);--> statement-breakpoint
CREATE VIEW "public"."divisions" AS (SELECT pk, name, name_short, abbreviation, league_pk, sport_pk, active FROM sqlmesh__public.public__divisions__3226860093);--> statement-breakpoint
CREATE VIEW "public"."leagues" AS (SELECT pk, name, abbreviation, name_short, sport_pk, active FROM sqlmesh__public.public__leagues__2544104352);--> statement-breakpoint
CREATE VIEW "public"."clubs" AS (SELECT pk, name, team_name, club_name, franchise_name, short_name, location_name, abbreviation, team_code, file_code, first_year_of_play, active, sport_pk, league_pk, division_pk, venue_pk FROM sqlmesh__public.public__clubs__1749365355);--> statement-breakpoint
CREATE VIEW "public"."plays" AS (SELECT pk, source_id, game_id, play_seq, season, game_date, inning, half_inning, batting_club_pk, pitching_club_pk, batter_pk, pitcher_pk, balls, strikes, outs_after, is_single, is_double, is_triple, is_home_run, is_walk, is_intentional_walk, is_hit_by_pitch, is_strikeout, is_sacrifice_fly, is_sacrifice_bunt, is_reached_on_error, is_fielders_choice, is_catcher_interference, is_double_play, is_triple_play, is_other_out, rbi, is_scoring_play, outs_recorded FROM sqlmesh__public.public__plays__2751775290);--> statement-breakpoint
CREATE VIEW "public"."venues" AS (SELECT pk, name, active, address1, address2, city, state, state_abbrev, postal_code, country, phone, elevation, azimuth_angle, latitude, longitude, time_zone_id, time_zone_abbreviation, time_zone_offset, capacity, turf_type, roof_type, field_left_line, field_left, field_left_center, field_center, field_right_center, field_right, field_right_line FROM sqlmesh__public.public__venues__1490727680);--> statement-breakpoint
CREATE VIEW "public"."play_sources" AS (SELECT source_id, source_name FROM sqlmesh__public.public__play_sources__3816633345);--> statement-breakpoint
CREATE VIEW "public"."pitcher_runs_charged" AS (SELECT pk, source_id, game_id, play_seq, season, pitcher_pk, is_earned FROM sqlmesh__public.public__pitcher_runs_charged__3179430887);--> statement-breakpoint
CREATE VIEW "public"."batting_stats_season" AS (SELECT batter_pk, season, pa, ab, h, singles, doubles, triples, home_runs, bb, ibb, hbp, so, sf, sh, tb, avg, obp, slg, ops, bb_pct, k_pct, bb_k, iso, babip, woba, wrc_plus, qualified FROM sqlmesh__public.public__batting_stats_season__2924712780);--> statement-breakpoint
CREATE VIEW "public"."park_factors" AS (SELECT pk, club_pk, season, basic_5yr, three_yr, one_yr, single, double, triple, hr, so, bb, gb, fb, ld, iffb, fip FROM sqlmesh__public.public__park_factors__4020210734);
*/