/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as BattingRouteImport } from "./routes/batting"
import { Route as GameGamePkRouteImport } from "./routes/game.$gamePk"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const BattingRoute = BattingRouteImport.update({
  id: "/batting",
  path: "/batting",
  getParentRoute: () => rootRouteImport,
} as any)
const GameGamePkRoute = GameGamePkRouteImport.update({
  id: "/game/$gamePk",
  path: "/game/$gamePk",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/batting": typeof BattingRoute
  "/game/$gamePk": typeof GameGamePkRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/batting": typeof BattingRoute
  "/game/$gamePk": typeof GameGamePkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/batting": typeof BattingRoute
  "/game/$gamePk": typeof GameGamePkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/batting" | "/game/$gamePk"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/batting" | "/game/$gamePk"
  id: "__root__" | "/" | "/batting" | "/game/$gamePk"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BattingRoute: typeof BattingRoute
  GameGamePkRoute: typeof GameGamePkRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/batting": {
      id: "/batting"
      path: "/batting"
      fullPath: "/batting"
      preLoaderRoute: typeof BattingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/game/$gamePk": {
      id: "/game/$gamePk"
      path: "/game/$gamePk"
      fullPath: "/game/$gamePk"
      preLoaderRoute: typeof GameGamePkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BattingRoute: BattingRoute,
  GameGamePkRoute: GameGamePkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
