/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as BattingRouteImport } from "./routes/batting"
import { Route as CustomQueryRouteImport } from "./routes/custom-query"
import { Route as PitchingRouteImport } from "./routes/pitching"
import { Route as BullpenIndexRouteImport } from "./routes/bullpen.index"
import { Route as BullpenClubRouteImport } from "./routes/bullpen.$club"
import { Route as GameGamePkRouteImport } from "./routes/game.$gamePk"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const BattingRoute = BattingRouteImport.update({
  id: "/batting",
  path: "/batting",
  getParentRoute: () => rootRouteImport,
} as any)
const CustomQueryRoute = CustomQueryRouteImport.update({
  id: "/custom-query",
  path: "/custom-query",
  getParentRoute: () => rootRouteImport,
} as any)
const PitchingRoute = PitchingRouteImport.update({
  id: "/pitching",
  path: "/pitching",
  getParentRoute: () => rootRouteImport,
} as any)
const BullpenIndexRoute = BullpenIndexRouteImport.update({
  id: "/bullpen/",
  path: "/bullpen/",
  getParentRoute: () => rootRouteImport,
} as any)
const BullpenClubRoute = BullpenClubRouteImport.update({
  id: "/bullpen/$club",
  path: "/bullpen/$club",
  getParentRoute: () => rootRouteImport,
} as any)
const GameGamePkRoute = GameGamePkRouteImport.update({
  id: "/game/$gamePk",
  path: "/game/$gamePk",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/batting": typeof BattingRoute
  "/custom-query": typeof CustomQueryRoute
  "/pitching": typeof PitchingRoute
  "/bullpen/$club": typeof BullpenClubRoute
  "/game/$gamePk": typeof GameGamePkRoute
  "/bullpen/": typeof BullpenIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/batting": typeof BattingRoute
  "/custom-query": typeof CustomQueryRoute
  "/pitching": typeof PitchingRoute
  "/bullpen/$club": typeof BullpenClubRoute
  "/game/$gamePk": typeof GameGamePkRoute
  "/bullpen": typeof BullpenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/batting": typeof BattingRoute
  "/custom-query": typeof CustomQueryRoute
  "/pitching": typeof PitchingRoute
  "/bullpen/$club": typeof BullpenClubRoute
  "/game/$gamePk": typeof GameGamePkRoute
  "/bullpen/": typeof BullpenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/batting"
    | "/custom-query"
    | "/pitching"
    | "/bullpen/$club"
    | "/game/$gamePk"
    | "/bullpen/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/batting"
    | "/custom-query"
    | "/pitching"
    | "/bullpen/$club"
    | "/game/$gamePk"
    | "/bullpen"
  id:
    | "__root__"
    | "/"
    | "/batting"
    | "/custom-query"
    | "/pitching"
    | "/bullpen/$club"
    | "/game/$gamePk"
    | "/bullpen/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BattingRoute: typeof BattingRoute
  CustomQueryRoute: typeof CustomQueryRoute
  PitchingRoute: typeof PitchingRoute
  BullpenClubRoute: typeof BullpenClubRoute
  GameGamePkRoute: typeof GameGamePkRoute
  BullpenIndexRoute: typeof BullpenIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/batting": {
      id: "/batting"
      path: "/batting"
      fullPath: "/batting"
      preLoaderRoute: typeof BattingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/custom-query": {
      id: "/custom-query"
      path: "/custom-query"
      fullPath: "/custom-query"
      preLoaderRoute: typeof CustomQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pitching": {
      id: "/pitching"
      path: "/pitching"
      fullPath: "/pitching"
      preLoaderRoute: typeof PitchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bullpen/": {
      id: "/bullpen/"
      path: "/bullpen"
      fullPath: "/bullpen/"
      preLoaderRoute: typeof BullpenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bullpen/$club": {
      id: "/bullpen/$club"
      path: "/bullpen/$club"
      fullPath: "/bullpen/$club"
      preLoaderRoute: typeof BullpenClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/game/$gamePk": {
      id: "/game/$gamePk"
      path: "/game/$gamePk"
      fullPath: "/game/$gamePk"
      preLoaderRoute: typeof GameGamePkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BattingRoute: BattingRoute,
  CustomQueryRoute: CustomQueryRoute,
  PitchingRoute: PitchingRoute,
  BullpenClubRoute: BullpenClubRoute,
  GameGamePkRoute: GameGamePkRoute,
  BullpenIndexRoute: BullpenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
